### ISSUE TITLE
Posts with URL don't show up as a link in Bluesky

### ISSUE THREAD

**Issue by elijahmanor** [eharris128/obsidian-bluesky#5]
I posted a new Bluesky entry using the plugin with a link, but in Bluesky it was not linkable

Example: https://bsky.app/profile/elijahmanor.com/post/3lbsajugcrg2n

I'm not sure if this is an issue with the plugin or an issue with the Bluesky API

> NOTE: Great plugin btw :)

**Comment by eharris128** [comment]
Probably on me.

I will look at this tomorrow.

Thank you for reporting :)

**Comment by eharris128** [comment]
Yup can confirm it is me.

The behavior inside the bsky app (which I will emulate)
![image](https://github.com/user-attachments/assets/4f309dba-f2b0-4c61-9f42-773c06e0dd7a)
